"""
Promotes blog posts from new_posts_data.py into the live site once their
scheduled published_date arrives. The post's HTML file already exists
(written earlier by generate-static-posts.py) but stays unlisted — not in
sitemap.xml, not on the blog listing grid, not linked from its game page —
until this script "promotes" it: adds the sitemap entry, the blog listing
card, and (if a matching game page exists) the backlink from that game page.

Meant to run once a day via cron. Idempotent — running it twice in the same
day, or after everything's already promoted, does nothing on the second run.

Usage:
    cd /www/wwwroot/allyonoindia.com
    python3 tools/publish-scheduled-posts.py
"""
import datetime
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
from new_posts_data import NEW_POSTS

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
SITEMAP_PATH = os.path.join(ROOT, "sitemap.xml")
BLOG_INDEX_PATH = os.path.join(ROOT, "blog", "index.html")

TODAY = datetime.date.today().isoformat()


def already_promoted(slug):
    sm = open(SITEMAP_PATH, encoding="utf-8").read()
    return f"https://allyonoindia.com/blog/{slug}/" in sm


def add_to_sitemap(post):
    sm = open(SITEMAP_PATH, encoding="utf-8").read()
    entry = (
        f'  <url>\n'
        f'    <loc>https://allyonoindia.com/blog/{post["slug"]}/</loc>\n'
        f'    <lastmod>{TODAY}</lastmod>\n'
        f'    <changefreq>monthly</changefreq>\n'
        f'    <priority>0.6</priority>\n'
        f'  </url>\n'
    )
    sm = sm.replace("</urlset>", entry + "</urlset>")
    open(SITEMAP_PATH, "w", encoding="utf-8").write(sm)


def add_to_blog_listing(post):
    html = open(BLOG_INDEX_PATH, encoding="utf-8").read()
    marker = "<!-- BLOG_GRID_START: auto-generated by tools/generate-blog-pages.py, do not hand-edit individual cards below -->"
    card = (
        f'\n        <a href="/blog/{post["slug"]}/" class="blog-card" style="text-decoration:none;grid-column:span 2">\n'
        f'          <img src="{post["cover_image"]}" alt="{post["image_alt"]}" width="1200" height="630" loading="lazy">\n'
        f'          <span class="tag">{post["eyebrow"]}</span>\n'
        f'          <h3>{post["title"]}</h3>\n'
        f'          <p>{post["meta_description"]}</p>\n'
        f'          <span class="read-more">Read the full post <span class="visually-hidden">about {post["title"]}</span></span>\n'
        f'        </a>'
    )
    if marker not in html:
        raise SystemExit("Could not find BLOG_GRID_START marker in blog/index.html")
    html = html.replace(marker, marker + card)
    open(BLOG_INDEX_PATH, "w", encoding="utf-8").write(html)


def add_game_page_backlink(post):
    game_slug = post["slug"].replace("-apk-download", "")
    game_path = os.path.join(ROOT, "all-yono-games", game_slug, "index.html")
    if not os.path.isfile(game_path):
        return False
    c = open(game_path, encoding="utf-8").read()
    if f"/blog/{post['slug']}/" in c:
        return True  # already linked
    old = '<p class="access-note" style="margin-top:12px">Login inside app only</p>'
    if old not in c:
        return False
    new = old + f'\n      <p>For setup steps, login safety checks, and more detail, see the <a href="/blog/{post["slug"]}/" style="color:var(--cyan);font-weight:700">{post["title"]}</a> on the blog.</p>'
    c = c.replace(old, new, 1)
    open(game_path, "w", encoding="utf-8").write(c)
    return True


def main():
    due = [p for p in NEW_POSTS if p.get("published_date", "9999-99-99") <= TODAY]
    promoted = []
    for post in due:
        if already_promoted(post["slug"]):
            continue
        add_to_sitemap(post)
        add_to_blog_listing(post)
        linked = add_game_page_backlink(post)
        promoted.append((post["slug"], linked))

    if not promoted:
        print(f"{TODAY}: nothing due to promote.")
        return

    for slug, linked in promoted:
        print(f"Promoted blog/{slug}/ (game-page backlink: {'added' if linked else 'no matching game page'})")

    subprocess.run(["git", "add", "-A"], cwd=ROOT, check=True)
    msg = "Publish scheduled post" + ("s" if len(promoted) > 1 else "") + ": " + ", ".join(s for s, _ in promoted)
    subprocess.run(["git", "commit", "-m", msg], cwd=ROOT, check=True)
    subprocess.run(["git", "push", "origin", "main"], cwd=ROOT, check=True)
    print("Committed and pushed.")


if __name__ == "__main__":
    main()
